android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25
  licenses:
    - 'android-sdk-license-.*'
jdk:
  - oraclejdk8

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
